import { useState } from 'react'
import './App.css'

const SERVICES = [
  {
    id: 'sales',
    name: 'Sales & Demand Generation',
    icon: '🚀',
    description: 'We build and manage go-to-market and outbound sales programmes across email, LinkedIn, phone, and video to build a qualified pipeline and close deals on your behalf.',
    tiers: [
      { id: 'starter', name: 'Starter', price: 1499, setup: 999, desc: 'Seed-funded companies building their first repeatable sales pipeline' },
      { id: 'grow', name: 'Grow', price: 2499, setup: 1299, desc: 'Series A companies scaling customer acquisition across multiple channels', popular: true },
      { id: 'scale', name: 'Scale', price: 4999, setup: 1799, desc: 'Series B companies accelerating revenue with comprehensive multi-channel outbound' },
    ],
    addons: [
      { id: 'sales-leads', name: 'Additional Leads Sourced & Enriched', price: 2.50, unit: '/lead', desc: 'Scale beyond the monthly lead allocation. Each lead is GDPR-compliant and enriched with verified emails, phone numbers, LinkedIn profiles, and company data.' },
      { id: 'sales-video', name: 'Video Outreach (SendSpark)', price: 14, unit: '/video', desc: 'Add hyper-personalised video outreach to your campaign. Includes custom script, professional recording with dynamic personalisation, hosting, and CRM integration.' },
      { id: 'sales-paid-lite', name: 'Paid Advertising Integration (Lite)', price: 799, unit: '/month', desc: 'Retarget your warmest accounts and turn outbound engagement into pipeline and closed revenue, faster.' },
      { id: 'sales-paid-full', name: 'Paid Advertising Integration (Full)', price: null, unit: 'Custom', desc: 'Unify your entire demand engine under one accountable team. We design and run the full paid media programme for your target accounts.' },
      { id: 'sales-email-domains', name: 'Additional Email Domains & Accounts', price: 199, unit: '/month', desc: 'An additional, fully-managed domain with 4 warmed email accounts, allowing you to send up to 200 more emails per day.' },
      { id: 'sales-linkedin', name: 'Additional LinkedIn Profiles', price: 399, unit: '/month', desc: 'Scale your LinkedIn outreach by adding more personal profiles. Each additional profile sends up to 30 connection requests daily with automated follow-ups.' },
      { id: 'sales-sdr', name: 'Dedicated SDR', price: 15, unit: '/hour', desc: 'Add specialist sales capacity to the team. Choose a dedicated full-time SDR or flexible part-time support.' },
    ]
  },
  {
    id: 'paid',
    name: 'Paid Advertising',
    icon: '📣',
    description: 'Accelerate your growth and acquire new customers with our fully managed ad campaigns across multiple digital channels including Google, Meta, TikTok, Pinterest, and more.',
    tiers: [
      { id: 'starter', name: 'Starter', price: 799, setup: 149, desc: 'For teams looking to acquire new customers across a search channel' },
      { id: 'grow', name: 'Grow', price: 1799, setup: 599, desc: 'Two or more paid media channels: Meta, TikTok, Pinterest, or LinkedIn', popular: true },
      { id: 'scale', name: 'Scale', price: 3899, setup: 1299, desc: 'Four or more: Mix search and social, or choose five social platforms' },
    ],
    addons: [
      { id: 'paid-meta', name: 'Meta Retargeting', price: 99, unit: '/month', desc: 'Re-engage your warm audiences on Facebook and Instagram, delivering targeted follow-up ads to high-intent prospects.' },
      { id: 'paid-display', name: 'Google Display Ads', price: 99, unit: '/month', desc: 'Add Google Display ads to an existing campaign for a small monthly fee. Effective at audience remarketing.' },
      { id: 'paid-shopping', name: 'Google Shopping Ads', price: 99, unit: '/month', desc: 'Add Google Shopping ads to an existing campaign. Includes the live product feed setup.' },
      { id: 'paid-call', name: 'Google Call Tracking Setup', price: 99, unit: ' one-time', desc: 'Implement call tracking for a one-time fee to track the number of calls generated by your ads.' },
      { id: 'paid-b2b', name: 'B2B Decision-Maker List Building & Targeting', price: 790, unit: ' one-time', desc: 'Prospect, validate, and connect with key decision-makers. We create GDPR-compliant prospect lists using verified data sources.' },
      { id: 'paid-warehouse', name: 'Data Warehouse Integration', price: 599, unit: ' one-time', desc: 'Integrate your social media channels through specific APIs into one unified repository, enabling real-time reporting.' },
      { id: 'paid-warehouse-opt', name: 'Data Warehouse Ongoing Optimisation', price: 119, unit: '/month', desc: 'Ongoing optimisation to maintain data accuracy, process speed, and attribution clarity.' },
      { id: 'paid-landing', name: 'Landing Page Design & Optimisation', price: 149, unit: '/month', desc: 'Dedicated support focused on designing and improving your landing page\'s design, layout, and user experience.' },
      { id: 'paid-zapier', name: 'Zapier Automation Management', price: 49, unit: '/month', desc: 'Streamline processes by connecting the apps you already use to automate repetitive tasks.' },
    ]
  },
  {
    id: 'email',
    name: 'Email Marketing',
    icon: '✉️',
    description: 'Maximise revenue with fully managed, personalised email campaigns that help increase advertising returns, retention and customer lifetime value.',
    tiers: [
      { id: 'starter', name: 'Starter', price: 799, setup: 249, desc: 'For early-stage SMEs looking to boost customer revenue' },
      { id: 'grow', name: 'Grow', price: 1499, setup: 249, desc: 'For growing SMEs looking to maximise customer lifetime value', popular: true },
      { id: 'scale', name: 'Scale', price: 3599, setup: 999, desc: 'For scaling SMEs looking to enhance customer loyalty' },
    ],
    addons: [
      { id: 'email-platform', name: 'Email Marketing on Any Platform', price: 79, unit: ' one-time', desc: 'Free migration services to the standard platforms. If you prefer another platform, we can do this for an additional cost.' },
      { id: 'email-sms', name: 'SMS Messaging Integration', price: 359, unit: '/month', desc: 'Complement email campaigns with SMS, WhatsApp, or other messaging. Our team will set up automated SMS campaigns and broadcasts.', recommended: true },
      { id: 'email-warehouse', name: 'Data Warehouse Integration', price: 599, unit: ' one-time', desc: 'Integrate your chosen email marketing platform through specific APIs into one unified repository.' },
      { id: 'email-warehouse-opt', name: 'Data Warehouse Ongoing Optimisation', price: 119, unit: '/month', desc: 'Ongoing optimisation to maintain data accuracy, process speed, and attribution clarity.' },
      { id: 'email-landing', name: 'Landing Page Design & Optimisation', price: 149, unit: '/month', desc: 'Dedicated support focused on designing and improving your landing page\'s design, layout, and user experience.', recommended: true },
      { id: 'email-zapier', name: 'Zapier Automation Management', price: 49, unit: '/month', desc: 'Set up and manage automated workflows ("Zaps") on your behalf for specific email marketing use cases.' },
    ]
  }
]

const DURATION_DISCOUNTS = { 3: 1, 6: 0.95, 12: 0.90 }

function ChevronDown({ open }) {
  return (
    <svg width="20" height="20" viewBox="0 0 20 20" fill="none" style={{ transform: open ? 'rotate(180deg)' : 'rotate(0)', transition: 'transform 0.25s ease' }}>
      <path d="M5 7.5L10 12.5L15 7.5" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  )
}

function CheckIcon() {
  return (
    <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
      <path d="M2 6L5 9L10 3" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  )
}

function Checkbox({ checked, onChange }) {
  return (
    <button
      className={`checkbox ${checked ? 'checked' : ''}`}
      onClick={(e) => { e.stopPropagation(); onChange(!checked) }}
      role="checkbox"
      aria-checked={checked}
    >
      {checked && <CheckIcon />}
    </button>
  )
}

function TierCard({ tier, selected, onSelect, discount }) {
  const monthlyPrice = Math.round(tier.price * discount)
  return (
    <div className={`tier-card ${selected ? 'selected' : ''}`} onClick={onSelect}>
      {tier.popular && <span className="popular-badge">POPULAR</span>}
      <div className="tier-radio">
        <div className={`radio ${selected ? 'selected' : ''}`}>
          {selected && <div className="radio-dot" />}
        </div>
      </div>
      <h4 className="tier-name">{tier.name}</h4>
      <p className="tier-desc">{tier.desc}</p>
      <div className="tier-pricing">
        <span className="tier-price">£{monthlyPrice.toLocaleString()}</span>
        <span className="tier-unit">/month</span>
      </div>
      <p className="tier-setup">+ £{tier.setup.toLocaleString()} setup fee</p>
    </div>
  )
}

function AddonCard({ addon, checked, onToggle }) {
  return (
    <div className={`addon-card ${checked ? 'selected' : ''}`}>
      <div className="addon-top">
        <Checkbox checked={checked} onChange={onToggle} />
        <div className="addon-info">
          <div className="addon-name-row">
            {addon.recommended && <span className="recommended-badge">RECOMMENDED</span>}
            <span className="addon-name">{addon.name}</span>
          </div>
          {addon.price !== null ? (
            <span className="addon-price">£{addon.price.toLocaleString()}<span className="addon-unit">{addon.unit}</span></span>
          ) : (
            <span className="addon-price custom-price">Custom</span>
          )}
        </div>
      </div>
      <p className="addon-desc">{addon.desc}</p>
    </div>
  )
}

function ServiceSection({ service, selections, onTierSelect, onAddonToggle, expanded, onToggleExpand, discount }) {
  const selectedTier = selections.tier
  const selectedAddons = selections.addons || {}

  return (
    <div className={`service-section ${expanded ? 'expanded' : ''} ${selectedTier ? 'has-selection' : ''}`}>
      <div className="service-header" onClick={onToggleExpand}>
        <div className="service-header-left">
          <Checkbox
            checked={!!selectedTier}
            onChange={() => {
              if (selectedTier) {
                onTierSelect(null)
              } else {
                const popularTier = service.tiers.find(t => t.popular) || service.tiers[0]
                onTierSelect(popularTier.id)
              }
            }}
          />
          <span className="service-icon">{service.icon}</span>
          <div className="service-text">
            <h3 className="service-name">{service.name}</h3>
          </div>
        </div>
        <ChevronDown open={expanded} />
      </div>

      {expanded && (
        <div className="service-body">
          <p className="service-desc">{service.description}</p>

          <div className="tiers-label">Select your plan</div>
          <div className="tiers-grid">
            {service.tiers.map(tier => (
              <TierCard
                key={tier.id}
                tier={tier}
                selected={selectedTier === tier.id}
                onSelect={() => onTierSelect(tier.id)}
                discount={discount}
              />
            ))}
          </div>

          {service.addons.length > 0 && (
            <div className="addons-section">
              <div className="addons-header">
                <span className="addons-icon">🧩</span>
                <h4>Add-ons</h4>
              </div>
              <p className="addons-subtitle">Enhance your core services or purchase standalone to maximise conversion rates and customer lifetime value.</p>
              <div className="addons-list">
                {service.addons.map(addon => (
                  <AddonCard
                    key={addon.id}
                    addon={addon}
                    checked={!!selectedAddons[addon.id]}
                    onToggle={(val) => onAddonToggle(addon.id, val)}
                  />
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  )
}

function SummaryPanel({ selections, duration, discount }) {
  const items = []
  let monthlyTotal = 0
  let oneTimeTotal = 0

  SERVICES.forEach(service => {
    const sel = selections[service.id]
    if (!sel || !sel.tier) return

    const tier = service.tiers.find(t => t.id === sel.tier)
    if (!tier) return

    const tierMonthly = Math.round(tier.price * discount)
    monthlyTotal += tierMonthly
    oneTimeTotal += tier.setup

    items.push({
      type: 'service',
      name: `${service.name}`,
      tier: tier.name,
      monthly: tierMonthly,
      setup: tier.setup,
      icon: service.icon,
    })

    if (sel.addons) {
      service.addons.forEach(addon => {
        if (!sel.addons[addon.id]) return
        if (addon.price === null) {
          items.push({ type: 'addon', name: addon.name, label: 'Custom pricing' })
          return
        }
        const isMonthly = addon.unit.includes('/month')
        if (isMonthly) {
          monthlyTotal += addon.price
          items.push({ type: 'addon', name: addon.name, monthly: addon.price })
        } else {
          oneTimeTotal += addon.price
          items.push({ type: 'addon', name: addon.name, oneTime: addon.price })
        }
      })
    }
  })

  const contractTotal = (monthlyTotal * duration) + oneTimeTotal
  const hasItems = items.length > 0

  return (
    <div className="summary-panel">
      <div className="summary-top">
        <h3 className="summary-title">Your Estimate</h3>
        <span className="summary-badge">{duration} mo</span>
      </div>

      <div className="summary-totals">
        <div className="summary-total-row main">
          <span>Monthly total</span>
          <span className="summary-amount">£{monthlyTotal.toLocaleString()}</span>
        </div>
        {oneTimeTotal > 0 && (
          <div className="summary-total-row">
            <span>One-time fees</span>
            <span className="summary-amount-sm">£{oneTimeTotal.toLocaleString()}</span>
          </div>
        )}
        <div className="summary-divider" />
        <div className="summary-total-row grand">
          <span>Est. {duration}-month total</span>
          <span className="summary-grand-total">£{contractTotal.toLocaleString()}</span>
        </div>
      </div>

      {hasItems ? (
        <div className="summary-items">
          <h4 className="summary-items-label">Selected Services</h4>
          {items.map((item, i) => (
            <div key={i} className={`summary-item ${item.type}`}>
              {item.type === 'service' && <span className="si-icon">{item.icon}</span>}
              {item.type === 'addon' && <span className="si-dot">+</span>}
              <div className="si-details">
                <span className="si-name">{item.name}</span>
                {item.tier && <span className="si-tier">{item.tier}</span>}
                <span className="si-price">
                  {item.monthly !== undefined && item.monthly > 0 && `£${item.monthly.toLocaleString()}/mo`}
                  {item.oneTime !== undefined && `£${item.oneTime.toLocaleString()} one-time`}
                  {item.label && item.label}
                </span>
                {item.setup !== undefined && (
                  <span className="si-setup">+ £{item.setup.toLocaleString()} setup</span>
                )}
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="summary-empty">
          <div className="summary-empty-icon">📋</div>
          <p>Select services to build your estimate</p>
        </div>
      )}

      {hasItems && (
        <button className="cta-button">Get Started →</button>
      )}
    </div>
  )
}

function App() {
  const [duration, setDuration] = useState(3)
  const [selections, setSelections] = useState({})
  const [expanded, setExpanded] = useState({})
  const discount = DURATION_DISCOUNTS[duration]

  const handleTierSelect = (serviceId, tierId) => {
    setSelections(prev => ({
      ...prev,
      [serviceId]: {
        ...prev[serviceId],
        tier: tierId,
        addons: tierId ? (prev[serviceId]?.addons || {}) : {}
      }
    }))
    if (tierId) {
      setExpanded(prev => ({ ...prev, [serviceId]: true }))
    }
  }

  const handleAddonToggle = (serviceId, addonId, value) => {
    setSelections(prev => ({
      ...prev,
      [serviceId]: {
        ...prev[serviceId],
        addons: {
          ...(prev[serviceId]?.addons || {}),
          [addonId]: value
        }
      }
    }))
  }

  const toggleExpand = (serviceId) => {
    setExpanded(prev => ({ ...prev, [serviceId]: !prev[serviceId] }))
  }

  return (
    <div className="app">
      <header className="page-header">
        <h1>Pricing Calculator</h1>
        <p>Configure your growth engine. Select services, choose your tier, and add enhancements.</p>
      </header>

      <div className="duration-tabs">
        {[3, 6, 12].map(d => (
          <button
            key={d}
            className={`duration-tab ${duration === d ? 'active' : ''}`}
            onClick={() => setDuration(d)}
          >
            {d} Months
            {d > 3 && <span className="discount-tag">Save {Math.round((1 - DURATION_DISCOUNTS[d]) * 100)}%</span>}
          </button>
        ))}
      </div>

      <div className="main-layout">
        <div className="services-col">
          {SERVICES.map(service => (
            <ServiceSection
              key={service.id}
              service={service}
              selections={selections[service.id] || {}}
              onTierSelect={(tierId) => handleTierSelect(service.id, tierId)}
              onAddonToggle={(addonId, val) => handleAddonToggle(service.id, addonId, val)}
              expanded={!!expanded[service.id]}
              onToggleExpand={() => toggleExpand(service.id)}
              discount={discount}
            />
          ))}
        </div>

        <div className="summary-col">
          <SummaryPanel selections={selections} duration={duration} discount={discount} />
        </div>
      </div>
    </div>
  )
}

export default App
